# Generated by Django 3.2.7 on 2021-09-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='Tags',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='project',
            name='Tags',
            field=models.ManyToManyField(to='portfolioWebsite.Tag'),
        ),
    ]
