# Generated by Django 3.2.7 on 2021-09-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioWebsite', '0002_auto_20210927_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='media')),
                ('Title', models.CharField(max_length=100)),
                ('SubTitle', models.CharField(max_length=120)),
            ],
        ),
    ]
