# Generated by Django 3.2.7 on 2021-09-29 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioWebsite', '0005_alter_feedback_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='contact_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
