# Generated by Django 3.2.7 on 2021-11-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioWebsite', '0007_auto_20211124_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='contact_email',
        ),
    ]
